### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by mhils** [chintal/documentedlist#2]
Hi,

Thanks again for the excellent project. We are using documentedlist for http://docs.mitmproxy.org/en/stable/features/filters.html and it work just great.
We are currently migrating everything to Python 3 - are there any plans to add Python 3 support? :smiley:

/cc @dufferzafar

**Comment by chintal** [comment]
I see only one unicode() call which should fail with python 3. I've now fixed that and bumped the version to 0.4. Let me know if you find any other python 3 compatibility issues.

**Comment by mhils** [comment]
Wow - I just upgraded our stuff and everything just works. Thanks so much! :smiley: :blush:
