### ISSUE TITLE
Please clarify licensing terms

### ISSUE THREAD

**Issue by lgbaldoni** [chintal/documentedlist#4]
Pypi says BSD-2-Clause, along with README.rst and sphinxcontrib/documentedlist.py.
Github says BSD-3-Clause and so does LICENSE.

I'm packaging this module for a linux distribution and I need to specify one of the two.

Thanks

**Comment by chintal** [comment]
My apologies. 

Fixed by changing the LICENSE text to the 2-clause license.

Thanks for your effort packaging this for a distribution!
